spring.application.name=employee_invex

server.port=8080
# URL de la base de datos (reemplaza 'tu_db' por el nombre de tu base)
spring.datasource.url=jdbc:mysql://localhost:3306/bd_invex
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Configuración de Hibernate/JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Nombre y ubicación del archivo
logging.file.name=logs/api-empleados.log

#Nivel de log para tu paquete específico
logging.level.com.tuproyecto.app=INFO

#Configurar la rotación (para que el archivo no pese gigas)
logging.logback.rollingpolicy.max-file-size=10MB
logging.logback.rollingpolicy.total-size-cap=100MB